# Generated by Django 4.0 on 2021-12-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=200)),
                ('name_province', models.CharField(max_length=200)),
                ('name_ville', models.CharField(max_length=200)),
                ('name_quartier', models.CharField(max_length=200)),
                ('name_avenue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GestionCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_africa.admin')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.cultureafrica')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_africa.country'),
        ),
    ]
