# Generated by Django 4.0 on 2021-12-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultureafrica',
            name='image',
            field=models.ImageField(null=True, upload_to='article/'),
        ),
    ]
