# Generated by Django 4.0 on 2021-12-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_cultureafrica_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultureafrica',
            name='image',
            field=models.FileField(null=True, upload_to='article/'),
        ),
    ]
